package com.financialauthority.database.ui.components

object UiText {
    private val labels = mapOf(
        "it" to mapOf(
            "countries" to "Paesi",
            "international" to "Autorità Internazionali",
            "search" to "Cerca",
            "favorites" to "Preferiti",
            "about" to "Informazioni",
            "loading" to "Caricamento dataset locali...",
            "error" to "Errore",
            "retry" to "Riprova",
            "no_results" to "Nessun risultato",
            "related" to "Collegamenti internazionali",
            "powers_limits" to "Poteri e limiti",
            "official_links" to "Link ufficiali",
            "additional_resources" to "Risorse e Link Ufficiali",
            "link_consumer_protection" to "🛡️ Risorse Protezione Consumatori",
            "link_financial_report" to "📄 Rapporto Mercati Finanziari",
            "link_supervision_legislation" to "⚖️ Supervisione e Legislazione",
            "link_press_releases" to "📰 Comunicati Stampa",
            "link_authorized_register" to "📋 Registro Imprese Autorizzate",
            "link_unauthorized_denunciation_form" to "🚨 Form Denuncia Entità Non Autorizzate",
            "link_fca_register" to "📋 Registro Ufficiale FCA",
            "link_prudential_regulation" to "🏛️ Prudential Regulation Authority",
            "link_consumer_education" to "🎓 Guida Educazione Finanziaria",
            "link_news_system_2026" to "📰 News da Authority - 14.09.2026 Nuovo sistema servizi al cittadino",
            "link_facebook" to "Facebook",
            "link_linkedin" to "LinkedIn",
            "link_instagram" to "Instagram",
            "link_tiktok" to "TikTok",
            "link_twitter" to "X-Twitter",
            "social_networks" to "Social Network Ufficiali",
            "download_app" to "Scarica App Ufficiale (Google Play)",
            "open_orbital_webapp" to "Orbital WebApp (Scheda Web)",
            "google_maps_location" to "Sede / Posizione Google Maps",
            "search_country_authority" to "Ricerca paese/autorità",
            "list_view" to "Vista lista",
            "grid_view" to "Vista griglia",
            "no_countries" to "Nessun paese trovato",
            "protection_level" to "Protezione",
            "official_homepage" to "Homepage ufficiale",
            "complaints_reports" to "Reclami/Segnalazioni",
            "email" to "Email",
            "add_favorite" to "Aggiungi preferito",
            "remove_favorite" to "Rimuovi preferito",
            "notes" to "Note",
            "international_links" to "Collegamenti internazionali",
            "badge_desc" to "Badge livello regione categoria tipo",
            "cannot_prefix" to "NON:",
            "fatf_note" to "FATF/GAFI: standard-setting e valutazioni reciproche; nessun potere investigativo, di sequestro o legislativo diretto.",
            "egmont_note" to "Egmont Group: rete globale di cooperazione tra FIU.",
            "uif_note" to "UIF: FIU nazionale italiana, non autorità globale unica.",
            "connected_institutions" to "Istituzioni collegate",
            "search_placeholder" to "Cerca (FATF, UIF, Italia, money laundering, Asia)",
            "no_favorites" to "Nessun preferito salvato",
            "about_subtitle" to "Servizio informativo offline-first su autorità finanziarie nazionali e internazionali.",
            "contacts" to "Contatti",
            "contacts_subtitle" to "Per aggiornamenti dataset e segnalazioni ufficiali usare sempre i siti istituzionali elencati.",
            "contacts_email" to "Email progetto web: vedi repository ufficiale",
            "language_selector" to "Selettore lingua",
            "all" to "Tutti",
            "fsrb_title" to "FSRB",
            "fiu_title" to "FIU"
        ),
        "en" to mapOf(
            "countries" to "Countries",
            "international" to "International Authorities",
            "search" to "Search",
            "favorites" to "Favorites",
            "about" to "About",
            "loading" to "Loading local datasets...",
            "error" to "Error",
            "retry" to "Retry",
            "no_results" to "No results",
            "related" to "International links",
            "powers_limits" to "Powers and limits",
            "official_links" to "Official links",
            "additional_resources" to "Official Resources & Links",
            "link_consumer_protection" to "🛡️ Consumer Protection Resources",
            "link_financial_report" to "📄 Financial Markets Report",
            "link_supervision_legislation" to "⚖️ Supervision & Legislation",
            "link_press_releases" to "📰 Press Releases",
            "link_authorized_register" to "📋 Authorized Firms Register",
            "link_unauthorized_denunciation_form" to "🚨 Report Unauthorized Entity",
            "link_fca_register" to "📋 Official FCA Register",
            "link_prudential_regulation" to "🏛️ Prudential Regulation Authority",
            "link_consumer_education" to "🎓 Financial Education Guide",
            "link_news_system_2026" to "📰 News by Authority - 14.09.2026 New citizen services system",
            "link_facebook" to "Facebook",
            "link_linkedin" to "LinkedIn",
            "link_instagram" to "Instagram",
            "link_tiktok" to "TikTok",
            "link_twitter" to "X-Twitter",
            "social_networks" to "Official Social Networks",
            "download_app" to "Download Official App (Google Play)",
            "open_orbital_webapp" to "Orbital WebApp (Web Card)",
            "google_maps_location" to "Google Maps Location",
            "search_country_authority" to "Search country/authority",
            "list_view" to "List view",
            "grid_view" to "Grid view",
            "no_countries" to "No countries found",
            "protection_level" to "Protection",
            "official_homepage" to "Official homepage",
            "complaints_reports" to "Complaints/Reports",
            "email" to "Email",
            "add_favorite" to "Add to favorites",
            "remove_favorite" to "Remove from favorites",
            "notes" to "Notes",
            "international_links" to "International links",
            "badge_desc" to "Level region category type badges",
            "cannot_prefix" to "NOT:",
            "fatf_note" to "FATF/GAFI: standard-setting and mutual evaluations; no direct investigative, seizure, or legislative power.",
            "egmont_note" to "Egmont Group: global network for FIU cooperation.",
            "uif_note" to "UIF: Italian national FIU, not a single global authority.",
            "connected_institutions" to "Connected institutions",
            "search_placeholder" to "Search (FATF, FIU, Italy, money laundering, Asia)",
            "no_favorites" to "No saved favorites",
            "about_subtitle" to "Offline-first information service on national and international financial authorities.",
            "contacts" to "Contacts",
            "contacts_subtitle" to "For dataset updates and official reports always use the listed institutional websites.",
            "contacts_email" to "Web project email: see official repository",
            "language_selector" to "Language selector",
            "all" to "All",
            "fsrb_title" to "FSRB",
            "fiu_title" to "FIU"
        )
    )

    fun get(locale: String, key: String): String = labels[locale]?.get(key)
        ?: labels["en"]?.get(key)
        ?: labels["it"]?.get(key)
        ?: key
}
